gestiondette/Models/Dette.cs
using gestiondette.Enum;

namespace gestiondette.Models
{
    public class Dette : AbstractEntity
    {





        private List<DetailDette>? detailDettes = new List<DetailDette>();
        private List<Paiement>? paiements = new List<Paiement>();

        private StateDette stateDette;

        // Constructor
        public Dette()
        {

        }

        // Properties

        public Client? Client { get; set; }
        public double MontantRestant { get; set; }
        public double MontantVerser { get; set; }
        public List<DetailDette>? DetailDettes { get; set; }
        public EtatDette EtatDette { get; set; }
        public double Montant { get; set; }
        public List<Paiement>? Paiements { get; set; } = new List<Paiement>();

        public StateDette StateDette { get; set; }

        // Methods




        public override string ToString()
        {
            return "Dette[" +
                    "id=" + Id +
                    ", montant=" + Montant +
                    ", montantRestant=" + MontantRestant +
                    ", montantVerser=" + MontantVerser +
                    ", etatDette=" + EtatDette +
                    ']';
        }
    }
}

gestiondette/Controllers/DetteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using gestiondette.Models;
using gestiondette.Enum;
using gestiondette.Helpers;

namespace gestiondette.Controllers
{
    public class DetteController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DetteController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Dette
        public async Task<IActionResult> Index(string status, int pageNumber = 1, int pageSize = 3)
        {
            var dettes = from d in _context.dette
                         select d;

            // Filter by status
            if (!string.IsNullOrEmpty(status))
            {
                if (status == "archiver")
                {
                    dettes = dettes.Where(d => d.StateDette == StateDette.ARCHIVER);
                }
                else if (status == "desarchiver")
                {
                    dettes = dettes.Where(d => d.StateDette == StateDette.DESARCHIVER);
                }
                else
                {
                    dettes = from d in _context.dette
                             select d; ;
                }
            }

            // Calculate total number of filtered items
            int totalClients = await dettes.CountAsync();

            // Apply pagination if pageSize > 0
            if (pageSize > 0)
            {
                dettes = dettes.Skip((pageNumber - 1) * pageSize).Take(pageSize);
            }

            // Calculate total pages based on pageSize
            int totalPages = (int)Math.Ceiling(totalClients / (double)pageSize);

            // Pass total pages and current page to ViewBag
            ViewBag.TotalPages = totalPages;
            ViewBag.CurrentPage = pageNumber;

            // Return the view with the paginated and filtered data
            return View(await dettes.ToListAsync());
        }



        // GET: Dette/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dette = await _context.dette
                .FirstOrDefaultAsync(m => m.Id == id);
            if (dette == null)
            {
                return NotFound();
            }


            return View(dette);
        }

        // GET: Dette/Create
        public async Task<IActionResult> Create()
        {

            var clients = await _context.client.ToListAsync();
            var articles = await _context.article.ToListAsync();
            ViewBag.Clients = clients;
            ViewBag.Articles = articles;
            var panier = HttpContext.Session.GetObjectFromJson<Panier>("panier") ?? new Panier();
            // HttpContext.Session.Remove("panier");
            ViewBag.panier = panier;
            // ViewBag.neub = "enabled";
            if (TempData["selectedClient"] != null)
            {

                int selectedClient = (int)TempData["selectedClient"];
                ViewBag.selectedClient = selectedClient;
                Console.WriteLine("******************************* cac'est mon idddddddddddddd  **************************");
                Console.WriteLine($"ClientId: {ViewBag.selectedClient}");
                Console.WriteLine("******************************* **************************");

                Client client = _context.client.FirstOrDefault(c => c.Id == selectedClient);

                Console.WriteLine("******************************* cac'est mon client  **************************");
                Console.WriteLine($"ClientId: {client}");
                Console.WriteLine("******************************* **************************");
                panier.client = client;
                HttpContext.Session.SetObjectAsJson("panier", panier);
                Console.WriteLine("******************************* cac'est mon panier  **************************");
                Console.WriteLine($"ClientId: {panier.client}");
                Console.WriteLine("******************************* **************************");
                // ViewBag.neub = "disabled";
                // Console.WriteLine(selectedClient);

            }




            return View();
        }

        [HttpPost]
        public async Task<IActionResult> create()
        {


            var panier = HttpContext.Session.GetObjectFromJson<Panier>("panier") ?? new Panier();
            var dette = new Dette();
            dette.StateDette = StateDette.DESARCHIVER;
            dette.CreateAt = DateTime.UtcNow;
            Console.WriteLine("******************************* **************************");
            Console.WriteLine("je suis la mon bbebebebebebbebebebebebebebbebbebe");
            Console.WriteLine(panier.client);
            Console.WriteLine("*************************************************************");

            int ClientId = panier.client.Id;

            dette.Client = _context.client.FirstOrDefault(c => c.Id == ClientId);
            double MontantTotal = 0.0;
            foreach (DetailDette detailDette in panier.detailDettes)
            {
                detailDette.Dette = dette;
                detailDette.ArticleId = detailDette.Article.Id;
                _context.Add(detailDette);
                MontantTotal += detailDette.Total;
            }
            dette.Montant = MontantTotal;
            dette.MontantRestant = MontantTotal;
            dette.MontantVerser = 0.0;
            dette.EtatDette = EtatDette.ENCOURS;
            dette.UpdateAt = DateTime.UtcNow;
            _context.Add(dette);
            await _context.SaveChangesAsync();
            HttpContext.Session.Remove("panier");
            return RedirectToAction(nameof(Index));
        }


        public IActionResult AjouterArticle(int articleId, int qte, string ClientId)
        {

            var article = _context.article.FirstOrDefault(a => a.Id == articleId);
            Console.WriteLine("'''''''''''''*************************************''''''''''''''''''''''''");
            Console.WriteLine($"Article: {article}, Quantity: {qte}");
            Console.WriteLine("''''''''''''************************************************************'''''''''''''''''''''''''");
            var panier = HttpContext.Session.GetObjectFromJson<Panier>("panier") ?? new Panier();


            panier.AjouterArticles(article, qte);
            HttpContext.Session.SetObjectAsJson("panier", panier);

            // Faire un dump du panier

            if (ViewBag.selectedClient == null)
            {
                ViewBag.selectedClient = Convert.ToInt32(ClientId);
                TempData["selectedClient"] = ViewBag.selectedClient; // Sto
                Console.WriteLine("******************************* **************************");
                Console.WriteLine($"ClientId: {ViewBag.selectedClient}");
                Console.WriteLine("******************************* **************************");
            }

            return RedirectToAction("Create");
        }

        // POST: Dette/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        // [HttpPost]
        // [ValidateAntiForgeryToken]
        // public async Task<IActionResult> Create(Dette dette)
        // {
        //     var id = int.Parse(Request.Form["ClientId"]!);


        //     if (ModelState.IsValid)
        //     {

        //         var client = await _context.client.FindAsync(id);

        //         if (client == null)
        //         {
        //             // Handle the case where the client is not found
        //             ModelState.AddModelError("", "Client not found.");
        //             return View(dette);
        //         }

        //         // Now set the full Client object to the Dette model
        //         dette.Client = client;
        //         dette.MontantVerser = 0.0;
        //         dette.MontantRestant = dette.Montant;
        //         dette.EtatDette = EtatDette.VALIDER;
        //         dette.StateDette = StateDette.DESARCHIVER;

        //         _context.Add(dette);
        //         await _context.SaveChangesAsync();
        //         return RedirectToAction(nameof(Index));
        //     }

        //     return View(dette);
        // }


        // GET: Dette/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dette = await _context.dette.FindAsync(id);
            if (dette == null)
            {
                return NotFound();
            }
            return View(dette);
        }

        // POST: Dette/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MontantRestant,MontantVerser,EtatDette,Montant,StateDette,Id,CreateAt,UpdateAt")] Dette dette)
        {
            if (id != dette.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(dette);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DetteExists(dette.Id))
                    {
                        return NotFound();
                    }
                    else

gestiondette/Controllers/PaiementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using gestiondette.Models;

namespace gestiondette.Controllers
{
    public class PaiementController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PaiementController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Paiement
        public async Task<IActionResult> Index(int id)
        {
            var paiements = await _context.paiement
                .Where(p => p.Dette.Id == id)
                .ToListAsync();

            ViewBag.DetteId = id; // Optionnel, pour utilisation dans la vue si besoin
            return View(paiements);
        }

        // GET: Paiement/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var paiement = await _context.paiement
                .FirstOrDefaultAsync(m => m.Id == id);
            if (paiement == null)
            {
                return NotFound();
            }

            return View(paiement);
        }

        public async Task<IActionResult> IndexByDette(int id)
        {
            var paiements = await _context.paiement
                .Where(p => p.Dette.Id == id)
                .ToListAsync();

            ViewBag.DetteId = id; // Optionnel, pour utilisation dans la vue si besoin
            return View(paiements);
        }

        // GET: Paiement/Create
        public IActionResult Create(int id)
        {
            if (id == null)
            {
                return NotFound("ID is missing.");
            }

            ViewData["DetteId"] = id;
            return View();
        }

        // POST: Paiement/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int Montant, int? id)
        {

            if (ModelState.IsValid)
            {
                var dette = await _context.dette.FindAsync(id);
                if (dette == null)
                {
                    return NotFound("Dette not found.");
                }
                if (Montant < dette.MontantRestant)
                {
                    Paiement paiement = new Paiement();

                    dette.MontantRestant -= Montant;
                    dette.MontantVerser += Montant;
                    paiement.DatePaiement = DateTime.UtcNow;
                    paiement.Montant = Montant;
                    paiement.Dette = dette;

                    _context.Add(paiement);

                    dette.Paiements.Add(paiement);
                    _context.dette.Update(dette);
                    await _context.SaveChangesAsync();
                    Console.WriteLine("-------------------************************************------------------------------");
                    Console.WriteLine(paiement.Id);
                    Console.WriteLine("----------------------**********************************---------------------------");
                    // return NotFound(paiement.Id);
                    return RedirectToAction("Index", new { id = dette.Id });
                }
                else
                {

                    ModelState.AddModelError("Montant", "montant invalide");
                }




            }
            return View();
        }

        // GET: Paiement/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var paiement = await _context.paiement.FindAsync(id);
            if (paiement == null)
            {
                return NotFound();
            }
            return View(paiement);
        }

        // POST: Paiement/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Montant,DatePaiement,Id,CreateAt,UpdateAt")] Paiement paiement)
        {
            if (id != paiement.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(paiement);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PaiementExists(paiement.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(paiement);
        }

        // GET: Paiement/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var paiement = await _context.paiement
                .FirstOrDefaultAsync(m => m.Id == id);
            if (paiement == null)
            {
                return NotFound();
            }

            return View(paiement);
        }

        // POST: Paiement/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var paiement = await _context.paiement.FindAsync(id);
            if (paiement != null)
            {
                _context.paiement.Remove(paiement);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PaiementExists(int id)
        {
            return _context.paiement.Any(e => e.Id == id);
        }
    }
}

gestiondette/Views/Dette/Create.cshtml
@model gestiondette.Models.Dette

@{
    Layout = "_layout";
}

<main class="p-4 sm:ml-64 overflow-hidden">
    <p class="bg-red-600">voici ton gars</p>
    <p>@ViewBag.selectedClient</p>
    <div class="flex flex-col justify-center items-center">
        <h1 class="text-3xl font-bold">Ajout Dette</h1>
        <div class="md:w-xgg sm:w-900 mx-auto p-6 border-t-black shadow-md border-2 rounded-md m-6">
            <form asp-action="AjouterArticle" method="post">
                <div class="">
                    <label for="Client">Client</label>
                    <select name="ClientId" id="Client"
                        class="p-2 mt-3 border border-gray-300 w-full rounded-md focus:outline-none focus:border-blue-500">
                        <option value="">Select a Client</option>
                        @if (ViewBag.Clients != null)
                        {

                            foreach (var client in ViewBag.Clients)
                            {
                                <option value="@client.Id" selected="@(ViewBag.selectedClient == client.Id )">
                                    @client.Surnom
                                </option>
                            }
                        }
                    </select>
                </div>
                <div class=" flex flex-row items-center space-x-4 mt-4 justify-between">
                    <div class="">
                        <label for="Client">Article</label>
                        <select name="ArticleId" id="Article"
                            class="p-2 mt-3 border border-gray-300 w-full rounded-md focus:outline-none focus:border-blue-500">
                            <option value="">Select a libelle</option>
                            @if (ViewBag.articles != null)
                            {
                                foreach (var article in ViewBag.articles)
                                {
                                    <option value="@article.Id">@article.Libelle</option>
                                }
                            }
                        </select>
                    </div>

                    <div class="">
                        <label for="Article">Montant</label>
                        <input type="number" name="qte"
                            class="p-2 mt-3 border border-gray-300 w-full rounded-md focus:outline-none focus:border-blue-500">

                    </div>

                    <div class="">
                        <button type="submit"
                            class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Ajouter</button>
                    </div>
                </div>
            </form>
            <form asp-action="create" method="post">
                <div asp-validation-summary="All" class="text-danger"></div>







                <div class="relative overflow-x-auto shadow-md sm:rounded-lg  mt-4">
                    <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
                        <thead
                            class="text-xs text-gray-700 uppercase  dark:bg-gray-700 dark:text-gray-400  bg-gray-900">
                            <tr>
                                <th scope="col" class="px-6 py-5 text-white">
                                    libelle
                                </th>
                                <th scope="col" class="px-6 py-5 text-white">
                                    montant
                                </th>
                                <th scope="col" class="px-6 py-5 text-white">
                                    quantite
                                </th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in ViewBag.panier.detailDettes)
                            {
                                <tr
                                    class="odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-b dark:border-gray-700">
                                    <td scope="row"
                                        class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                                        @item.Article.Libelle
                                    </td>
                                    <td scope="row"
                                        class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                                        @item.Total
                                    </td>
                                    <td scope="row"
                                        class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                                        @item.Qte
                                    </td>

                                </tr>
                            }
                        </tbody>
                    </table>

                </div>
                <div class="w-full flex justify-end mt-6">
                    <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                        Save
                    </button>
                </div>
            </form>
        </div>
    </div>
</main>

gestiondette/Views/Dette/Create1.cshtml
@model gestiondette.Models.Dette

@{
    Layout = "_layout";
}


<main class="p-4 sm:ml-64 overflow-hidden">
    <div class="flex flex-col justify-center items-center">
        <h1 class="text-3xl font-bold">Ajout Dette</h1>
        <div class="md:w-xgg sm:w-900 mx-auto p-6 border-t-black shadow-md border-2 rounded-md m-6">
            <form asp-action="Create" method="post">
                <div asp-validation-summary="All" class="text-danger"></div>


                <div class="">
                    <label for="Client">Client</label>
                    <select name="ClientId" id="Client"
                        class="p-2 mt-3 border border-gray-300 w-full rounded-md focus:outline-none focus:border-blue-500">
                        <option value="">Select a Client</option>
                        @if (ViewBag.Clients != null)
                        {
                            foreach (var client in ViewBag.Clients)
                            {
                                <option value="@client.Id">@client.Surnom</option>
                            }
                        }
                    </select>
                </div>

                <div class="flex flex-row">
                    <div class="">
                        <label for="Client">Client</label>
                        <select name="ClientId" id="Client"
                            class="p-2 mt-3 border border-gray-300 w-full rounded-md focus:outline-none focus:border-blue-500">
                            <option value="">Select a Client</option>
                            @if (ViewBag.Clients != null)
                            {
                                foreach (var client in ViewBag.Clients)
                                {
                                    <option value="@client.Id">@client.Surnom</option>
                                }
                            }
                        </select>
                    </div>

                </div>

            </form>
        </div>
    </div>


</main>

gestiondette/Views/Dette/Delete.cshtml
@model gestiondette.Models.Dette

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Dette</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MontantRestant)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MontantRestant)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MontantVerser)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MontantVerser)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EtatDette)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EtatDette)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Montant)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Montant)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StateDette)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StateDette)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreateAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreateAt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdateAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdateAt)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
</body>
</html>

gestiondette/Views/Dette/Details.cshtml
@model gestiondette.Models.Dette

@{
    Layout = "_layout";
}

<main class="p-6 sm:ml-64 overflow-hidden bg-gray-50">
    <div class="flex flex-col justify-center items-center">
        <div class="w-full  flex justify-end">
            <a href="@Url.Action("Create", "Paiement", new { id = Model.Id })"
                class="p-4 text-white bg-blue-400 rounded-lg">
                Faire Paiement
            </a>
        </div>
        <h1 class="text-4xl font-semibold text-gray-800 mb-6">Detail Dette</h1>

        <!-- Card Container for Content -->
        <div class="w-full sm:w-4/5 md:w-1/2 mx-auto p-6 bg-white border-t-4 border-blue-500 shadow-lg rounded-lg">
            <div class="flex flex-col gap-6">
                <!-- Each term (dt) and description (dd) inside flex containers with inputs for values -->
                <div class="flex flex-col">
                    <label for="MontantRestant" class="text-lg font-medium text-gray-700">Montant Restant</label>
                    <input type="text" id="MontantRestant" name="MontantRestant"
                        value="@Html.DisplayFor(model => model.MontantRestant)"
                        class="mt-2 p-2 border border-gray-300 rounded-md text-gray-500" readonly />
                </div>
                <div class="flex flex-col">
                    <label for="MontantVerser" class="text-lg font-medium text-gray-700">Montant Versé</label>
                    <input type="text" id="MontantVerser" name="MontantVerser"
                        value="@Html.DisplayFor(model => model.MontantVerser)"
                        class="mt-2 p-2 border border-gray-300 rounded-md text-gray-500" readonly />
                </div>
                <div class="flex flex-col">
                    <label for="EtatDette" class="text-lg font-medium text-gray-700">État Dette</label>
                    <input type="text" id="EtatDette" name="EtatDette"
                        value="@Html.DisplayFor(model => model.EtatDette)"
                        class="mt-2 p-2 border border-gray-300 rounded-md text-gray-500" readonly />
                </div>
                <div class="flex flex-col">
                    <label for="Montant" class="text-lg font-medium text-gray-700">Montant</label>
                    <input type="text" id="Montant" name="Montant" value="@Html.DisplayFor(model => model.Montant)"
                        class="mt-2 p-2 border border-gray-300 rounded-md text-gray-500" readonly />
                </div>
                <div class="flex flex-col">
                    <label for="StateDette" class="text-lg font-medium text-gray-700">État de la Dette</label>
                    <input type="text" id="StateDette" name="StateDette"
                        value="@Html.DisplayFor(model => model.StateDette)"
                        class="mt-2 p-2 border border-gray-300 rounded-md text-gray-500" readonly />
                </div>
            </div>
        </div>

        <!-- Action Links -->
        <div class="mt-6 text-center">
            <a href="@Url.Action("Edit", new { id = Model?.Id })" class="text-blue-600 hover:underline mx-4">Edit</a> |
            <a href="@Url.Action("Index")" class="text-blue-600 hover:underline mx-4">Back to List</a>
        </div>
    </div>
</main>